### ISSUE TITLE
Add advanced dialog widget

### ISSUE THREAD

**Issue by DanicaSTFC** [TomographicImaging/eqt#100]
This dialog could have widgets which take user inputs, a set default button, Ok and Cancel. When the values are not set to default, qlabel widgets will be created in the parent widget to show the user selection. When the values are set to default, the widgets in the parent will either hide or be removed.

**Comment by lauramurgatroyd** [comment]
Operating on a parent should not be done from within a child.
The connecting methods should be made in the parent.
