### ISSUE TITLE
Developer documentation on how to synchronise the local pre-commit to the github precommit

### ISSUE THREAD

**Issue by DanicaSTFC** [TomographicImaging/eqt#127]
When the pre-commit is updated in the repository on GitHub, there should be an easy/automatic way for the developers to update their local pre-commit checker. The developer should be informed when the pre-commit checks are updated and the documentation should show instructions on how to set the checker locally so that it is exactly the same as the one on the repository online.

**Comment by paskino** [comment]
Probably need to check https://github.com/TomographicImaging/eqt/blob/main/CONTRIBUTING.md

**Comment by casperdcl** [comment]
yup, your local `pre-commit` should autoupdate itself if you pull & merge `main` locally.
