### ISSUE TITLE
Add methods to remove widgets from forms

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/eqt#70]
In the form interface we have methods to add widgets to the forms, and get widgets from the forms, but we don't have any methods to remove widgets:
https://github.com/TomographicImaging/eqt/blob/7cb5e13486b6d45772b698c78edca3f957112007/eqt/ui/UIFormWidget.py#L55-L69

I propose we add a method 'removeWidget' which takes the name of the widget, and this would remove any widgets of that name which have either the 'label' or 'field' role.

Resolving this issue would involve:

- [ ]  Adding a removeWidget method to UIFormWidget
- [ ]  Adding a removeWidget method to FormDockWidget (https://github.com/TomographicImaging/eqt/blob/7cb5e13486b6d45772b698c78edca3f957112007/eqt/ui/UIFormWidget.py#L314)
- [ ]  Adding a removeWidget method to FormDialog (https://github.com/TomographicImaging/eqt/blob/7cb5e13486b6d45772b698c78edca3f957112007/eqt/ui/FormDialog.py#L6)
- [ ] Add an example of using removeWidget to a dialog example: https://github.com/TomographicImaging/eqt/blob/main/examples/dialog_example_2.py

**Comment by paskino** [comment]
Please add unittest in https://github.com/TomographicImaging/eqt/blob/main/test/test__formUI_status_test.py

**Comment by paskino** [comment]
Also, the dictionary with the widget and label references should be updated and the references removed.

Here they are added 

https://github.com/TomographicImaging/eqt/blob/bb0be3aa5ec74dd6942923ebb613390d1c5b9cbf/eqt/ui/UIFormWidget.py#L118C9-L118C38
https://github.com/TomographicImaging/eqt/blob/bb0be3aa5ec74dd6942923ebb613390d1c5b9cbf/eqt/ui/UIFormWidget.py#L130
