### ISSUE TITLE
Add documentation on the github-actions

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/eqt#86]
This should briefly cover what the actions do, and how the change log can easily be accessed.

This may be best placed in a `*.md` file in .github/workflows or alternatively, we could start making a developers guide within a new 'docs' folder

**Comment by casperdcl** [comment]
already in https://github.com/TomographicImaging/eqt/blob/main/CONTRIBUTING.md (which is [the canonical location](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors))?

**Comment by lauramurgatroyd** [comment]
Sorry I missed it!
