### ISSUE TITLE
Add widget number to dictionary

### ISSUE THREAD

**Issue by DanicaSTFC** [TomographicImaging/eqt#95]
https://github.com/TomographicImaging/eqt/blob/abf3fc015ca8b552ceffe3bb933cef7aaf17b240/eqt/ui/UIFormWidget.py#L109

The dictionary could store the information of the widget's row number in the layout (its allocated number).

**Comment by lauramurgatroyd** [comment]
I think this would work better as a separate dictionary to the dictionary stored in self.widgets

**Comment by DanicaSTFC** [comment]
We decide to call this `widget_row` in PR #109
